### ISSUE TITLE
Generate eloquent-filter not working

### ISSUE THREAD

**Issue by alasdairmackenzie** [pricecurrent/laravel-eloquent-filters#6]
I've just installed the package and run the `artisan make:eloquent-filter` command but it isn't working. It looks like it's because the latest package changes need to be published to reflect the master branch. The old `artisan eloquent-filter:make` works.

(Nice work, btw. I really like the approach).

**Comment by pricecurrent** [comment]
Thank you @alasdairmackenzie 

New release is published and seems to have fixed the issue. Completely new to the open-source world here. Is it every time master branch gets updated a new release should be published?

Is there any good resources to learn how to manage open-source project? I've tried following the Laracasts series but I believe there he would just merge/push to master branch and it would become available

**Comment by pricecurrent** [comment]
fixed with the new release - clsosing
